<?xml version="1.0" encoding="utf-8"?><Database Name="Plapsa" Class="FacturacionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JORGE-EXO-PC\MSSQL;Initial Catalog=Plapsa;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="PlapsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Historicos" Member="Historicos">
    <Type Name="Historicos">
      <Column Name="historico_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mediopago_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fec_descarga" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="contrato_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fec_cobro" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="hora_cobro" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="importe" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="canal_pago" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_control" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_terminal" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_barras" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_pagoelectronico" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="fec_informado" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="hora_informado" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="codigorechazo_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigodemorado_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo_consorcio" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="codigo_unidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comision" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="iva" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="neto" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="ordenpago_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="fec_transferencia" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="transaccion_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="factura_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mp_comision" Type="System.Decimal" DbType="Decimal(8,4) NOT NULL" CanBeNull="false" />
      <Column Name="mp_iva" Type="System.Decimal" DbType="Decimal(8,4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Puntos_Ventas" Member="Puntos_Ventas">
    <Type Name="Puntos_Ventas">
      <Column Name="puntoventa_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nro_ult_fac_a" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nro_ult_fac_b" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="cod_postal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Codigos_Iva" Member="Codigos_Iva">
    <Type Name="Codigos_Iva">
      <Column Name="codigoiva_id" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="condicion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Contratos" Member="Contratos">
    <Type Name="Contratos">
      <Column Name="contrato_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="denominacion" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="codpostal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigoiva_id" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="cuit" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="web" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="mail_rendicion_1" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="mail_rendicion_2" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="envio_archivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mail_ordenpago_1" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="mail_ordenpago_2" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="mail_confidencial_1" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="mail_confidencial_2" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="suspendido" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="porc_administrador" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="cbu_1_administrador" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="cbu_2_administrador" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="concentrador_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vendedor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="porc_descuento" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="clave_web" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="afip_denominacion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="afip_direccion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="afip_codpostal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="facturar_cons" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="usuario_web" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ripsa_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="ripsa_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="rapipago_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="rapipago_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="bapro_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="bapro_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="link_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="link_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="pagomiscuentas_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="pagomiscuentas_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="nacion_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="nacion_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="galicia_min" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="galicia_porcen" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="puntoventa_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Facturas" Member="Facturas">
    <Type Name="Facturas">
      <Column Name="factura_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="puntoventa_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nro_factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_factura" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="contrato_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="concepto" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="importe" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="iva" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="neto" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>