#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Plapsa")]
	public partial class FacturacionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertHistoricos(Historicos instance);
    partial void UpdateHistoricos(Historicos instance);
    partial void DeleteHistoricos(Historicos instance);
    partial void InsertPuntos_Ventas(Puntos_Ventas instance);
    partial void UpdatePuntos_Ventas(Puntos_Ventas instance);
    partial void DeletePuntos_Ventas(Puntos_Ventas instance);
    partial void InsertCodigos_Iva(Codigos_Iva instance);
    partial void UpdateCodigos_Iva(Codigos_Iva instance);
    partial void DeleteCodigos_Iva(Codigos_Iva instance);
    partial void InsertContratos(Contratos instance);
    partial void UpdateContratos(Contratos instance);
    partial void DeleteContratos(Contratos instance);
    partial void InsertFacturas(Facturas instance);
    partial void UpdateFacturas(Facturas instance);
    partial void DeleteFacturas(Facturas instance);
    #endregion
		
		public FacturacionDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.PlapsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FacturacionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FacturacionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FacturacionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FacturacionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Historicos> Historicos
		{
			get
			{
				return this.GetTable<Historicos>();
			}
		}
		
		public System.Data.Linq.Table<Puntos_Ventas> Puntos_Ventas
		{
			get
			{
				return this.GetTable<Puntos_Ventas>();
			}
		}
		
		public System.Data.Linq.Table<Codigos_Iva> Codigos_Iva
		{
			get
			{
				return this.GetTable<Codigos_Iva>();
			}
		}
		
		public System.Data.Linq.Table<Contratos> Contratos
		{
			get
			{
				return this.GetTable<Contratos>();
			}
		}
		
		public System.Data.Linq.Table<Facturas> Facturas
		{
			get
			{
				return this.GetTable<Facturas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Historicos")]
	public partial class Historicos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _historico_id;
		
		private int _mediopago_id;
		
		private System.DateTime _fec_descarga;
		
		private int _contrato_id;
		
		private System.DateTime _fec_cobro;
		
		private string _hora_cobro;
		
		private decimal _importe;
		
		private string _canal_pago;
		
		private string _codigo_control;
		
		private string _codigo_terminal;
		
		private string _codigo_barras;
		
		private string _codigo_pagoelectronico;
		
		private System.DateTime _fec_informado;
		
		private string _hora_informado;
		
		private int _codigorechazo_id;
		
		private int _codigodemorado_id;
		
		private short _codigo_consorcio;
		
		private int _codigo_unidad;
		
		private decimal _comision;
		
		private decimal _iva;
		
		private decimal _neto;
		
		private long _ordenpago_id;
		
		private System.DateTime _fec_transferencia;
		
		private long _transaccion_id;
		
		private int _factura_id;
		
		private decimal _mp_comision;
		
		private decimal _mp_iva;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhistorico_idChanging(long value);
    partial void Onhistorico_idChanged();
    partial void Onmediopago_idChanging(int value);
    partial void Onmediopago_idChanged();
    partial void Onfec_descargaChanging(System.DateTime value);
    partial void Onfec_descargaChanged();
    partial void Oncontrato_idChanging(int value);
    partial void Oncontrato_idChanged();
    partial void Onfec_cobroChanging(System.DateTime value);
    partial void Onfec_cobroChanged();
    partial void Onhora_cobroChanging(string value);
    partial void Onhora_cobroChanged();
    partial void OnimporteChanging(decimal value);
    partial void OnimporteChanged();
    partial void Oncanal_pagoChanging(string value);
    partial void Oncanal_pagoChanged();
    partial void Oncodigo_controlChanging(string value);
    partial void Oncodigo_controlChanged();
    partial void Oncodigo_terminalChanging(string value);
    partial void Oncodigo_terminalChanged();
    partial void Oncodigo_barrasChanging(string value);
    partial void Oncodigo_barrasChanged();
    partial void Oncodigo_pagoelectronicoChanging(string value);
    partial void Oncodigo_pagoelectronicoChanged();
    partial void Onfec_informadoChanging(System.DateTime value);
    partial void Onfec_informadoChanged();
    partial void Onhora_informadoChanging(string value);
    partial void Onhora_informadoChanged();
    partial void Oncodigorechazo_idChanging(int value);
    partial void Oncodigorechazo_idChanged();
    partial void Oncodigodemorado_idChanging(int value);
    partial void Oncodigodemorado_idChanged();
    partial void Oncodigo_consorcioChanging(short value);
    partial void Oncodigo_consorcioChanged();
    partial void Oncodigo_unidadChanging(int value);
    partial void Oncodigo_unidadChanged();
    partial void OncomisionChanging(decimal value);
    partial void OncomisionChanged();
    partial void OnivaChanging(decimal value);
    partial void OnivaChanged();
    partial void OnnetoChanging(decimal value);
    partial void OnnetoChanged();
    partial void Onordenpago_idChanging(long value);
    partial void Onordenpago_idChanged();
    partial void Onfec_transferenciaChanging(System.DateTime value);
    partial void Onfec_transferenciaChanged();
    partial void Ontransaccion_idChanging(long value);
    partial void Ontransaccion_idChanged();
    partial void Onfactura_idChanging(int value);
    partial void Onfactura_idChanged();
    partial void Onmp_comisionChanging(decimal value);
    partial void Onmp_comisionChanged();
    partial void Onmp_ivaChanging(decimal value);
    partial void Onmp_ivaChanged();
    #endregion
		
		public Historicos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_historico_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long historico_id
		{
			get
			{
				return this._historico_id;
			}
			set
			{
				if ((this._historico_id != value))
				{
					this.Onhistorico_idChanging(value);
					this.SendPropertyChanging();
					this._historico_id = value;
					this.SendPropertyChanged("historico_id");
					this.Onhistorico_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediopago_id", DbType="Int NOT NULL")]
		public int mediopago_id
		{
			get
			{
				return this._mediopago_id;
			}
			set
			{
				if ((this._mediopago_id != value))
				{
					this.Onmediopago_idChanging(value);
					this.SendPropertyChanging();
					this._mediopago_id = value;
					this.SendPropertyChanged("mediopago_id");
					this.Onmediopago_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_descarga", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fec_descarga
		{
			get
			{
				return this._fec_descarga;
			}
			set
			{
				if ((this._fec_descarga != value))
				{
					this.Onfec_descargaChanging(value);
					this.SendPropertyChanging();
					this._fec_descarga = value;
					this.SendPropertyChanged("fec_descarga");
					this.Onfec_descargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrato_id", DbType="Int NOT NULL")]
		public int contrato_id
		{
			get
			{
				return this._contrato_id;
			}
			set
			{
				if ((this._contrato_id != value))
				{
					this.Oncontrato_idChanging(value);
					this.SendPropertyChanging();
					this._contrato_id = value;
					this.SendPropertyChanged("contrato_id");
					this.Oncontrato_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_cobro", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fec_cobro
		{
			get
			{
				return this._fec_cobro;
			}
			set
			{
				if ((this._fec_cobro != value))
				{
					this.Onfec_cobroChanging(value);
					this.SendPropertyChanging();
					this._fec_cobro = value;
					this.SendPropertyChanged("fec_cobro");
					this.Onfec_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_cobro", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string hora_cobro
		{
			get
			{
				return this._hora_cobro;
			}
			set
			{
				if ((this._hora_cobro != value))
				{
					this.Onhora_cobroChanging(value);
					this.SendPropertyChanging();
					this._hora_cobro = value;
					this.SendPropertyChanged("hora_cobro");
					this.Onhora_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_importe", DbType="Decimal(8,2) NOT NULL")]
		public decimal importe
		{
			get
			{
				return this._importe;
			}
			set
			{
				if ((this._importe != value))
				{
					this.OnimporteChanging(value);
					this.SendPropertyChanging();
					this._importe = value;
					this.SendPropertyChanged("importe");
					this.OnimporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canal_pago", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string canal_pago
		{
			get
			{
				return this._canal_pago;
			}
			set
			{
				if ((this._canal_pago != value))
				{
					this.Oncanal_pagoChanging(value);
					this.SendPropertyChanging();
					this._canal_pago = value;
					this.SendPropertyChanged("canal_pago");
					this.Oncanal_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_control", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigo_control
		{
			get
			{
				return this._codigo_control;
			}
			set
			{
				if ((this._codigo_control != value))
				{
					this.Oncodigo_controlChanging(value);
					this.SendPropertyChanging();
					this._codigo_control = value;
					this.SendPropertyChanged("codigo_control");
					this.Oncodigo_controlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_terminal", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigo_terminal
		{
			get
			{
				return this._codigo_terminal;
			}
			set
			{
				if ((this._codigo_terminal != value))
				{
					this.Oncodigo_terminalChanging(value);
					this.SendPropertyChanging();
					this._codigo_terminal = value;
					this.SendPropertyChanged("codigo_terminal");
					this.Oncodigo_terminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_barras", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string codigo_barras
		{
			get
			{
				return this._codigo_barras;
			}
			set
			{
				if ((this._codigo_barras != value))
				{
					this.Oncodigo_barrasChanging(value);
					this.SendPropertyChanging();
					this._codigo_barras = value;
					this.SendPropertyChanged("codigo_barras");
					this.Oncodigo_barrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_pagoelectronico", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string codigo_pagoelectronico
		{
			get
			{
				return this._codigo_pagoelectronico;
			}
			set
			{
				if ((this._codigo_pagoelectronico != value))
				{
					this.Oncodigo_pagoelectronicoChanging(value);
					this.SendPropertyChanging();
					this._codigo_pagoelectronico = value;
					this.SendPropertyChanged("codigo_pagoelectronico");
					this.Oncodigo_pagoelectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_informado", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fec_informado
		{
			get
			{
				return this._fec_informado;
			}
			set
			{
				if ((this._fec_informado != value))
				{
					this.Onfec_informadoChanging(value);
					this.SendPropertyChanging();
					this._fec_informado = value;
					this.SendPropertyChanged("fec_informado");
					this.Onfec_informadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_informado", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string hora_informado
		{
			get
			{
				return this._hora_informado;
			}
			set
			{
				if ((this._hora_informado != value))
				{
					this.Onhora_informadoChanging(value);
					this.SendPropertyChanging();
					this._hora_informado = value;
					this.SendPropertyChanged("hora_informado");
					this.Onhora_informadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigorechazo_id", DbType="Int NOT NULL")]
		public int codigorechazo_id
		{
			get
			{
				return this._codigorechazo_id;
			}
			set
			{
				if ((this._codigorechazo_id != value))
				{
					this.Oncodigorechazo_idChanging(value);
					this.SendPropertyChanging();
					this._codigorechazo_id = value;
					this.SendPropertyChanged("codigorechazo_id");
					this.Oncodigorechazo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigodemorado_id", DbType="Int NOT NULL")]
		public int codigodemorado_id
		{
			get
			{
				return this._codigodemorado_id;
			}
			set
			{
				if ((this._codigodemorado_id != value))
				{
					this.Oncodigodemorado_idChanging(value);
					this.SendPropertyChanging();
					this._codigodemorado_id = value;
					this.SendPropertyChanged("codigodemorado_id");
					this.Oncodigodemorado_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_consorcio", DbType="SmallInt NOT NULL")]
		public short codigo_consorcio
		{
			get
			{
				return this._codigo_consorcio;
			}
			set
			{
				if ((this._codigo_consorcio != value))
				{
					this.Oncodigo_consorcioChanging(value);
					this.SendPropertyChanging();
					this._codigo_consorcio = value;
					this.SendPropertyChanged("codigo_consorcio");
					this.Oncodigo_consorcioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_unidad", DbType="Int NOT NULL")]
		public int codigo_unidad
		{
			get
			{
				return this._codigo_unidad;
			}
			set
			{
				if ((this._codigo_unidad != value))
				{
					this.Oncodigo_unidadChanging(value);
					this.SendPropertyChanging();
					this._codigo_unidad = value;
					this.SendPropertyChanged("codigo_unidad");
					this.Oncodigo_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comision", DbType="Decimal(6,2) NOT NULL")]
		public decimal comision
		{
			get
			{
				return this._comision;
			}
			set
			{
				if ((this._comision != value))
				{
					this.OncomisionChanging(value);
					this.SendPropertyChanging();
					this._comision = value;
					this.SendPropertyChanged("comision");
					this.OncomisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iva", DbType="Decimal(6,2) NOT NULL")]
		public decimal iva
		{
			get
			{
				return this._iva;
			}
			set
			{
				if ((this._iva != value))
				{
					this.OnivaChanging(value);
					this.SendPropertyChanging();
					this._iva = value;
					this.SendPropertyChanged("iva");
					this.OnivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neto", DbType="Decimal(8,2) NOT NULL")]
		public decimal neto
		{
			get
			{
				return this._neto;
			}
			set
			{
				if ((this._neto != value))
				{
					this.OnnetoChanging(value);
					this.SendPropertyChanging();
					this._neto = value;
					this.SendPropertyChanged("neto");
					this.OnnetoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordenpago_id", DbType="BigInt NOT NULL")]
		public long ordenpago_id
		{
			get
			{
				return this._ordenpago_id;
			}
			set
			{
				if ((this._ordenpago_id != value))
				{
					this.Onordenpago_idChanging(value);
					this.SendPropertyChanging();
					this._ordenpago_id = value;
					this.SendPropertyChanged("ordenpago_id");
					this.Onordenpago_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_transferencia", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fec_transferencia
		{
			get
			{
				return this._fec_transferencia;
			}
			set
			{
				if ((this._fec_transferencia != value))
				{
					this.Onfec_transferenciaChanging(value);
					this.SendPropertyChanging();
					this._fec_transferencia = value;
					this.SendPropertyChanged("fec_transferencia");
					this.Onfec_transferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaccion_id", DbType="BigInt NOT NULL")]
		public long transaccion_id
		{
			get
			{
				return this._transaccion_id;
			}
			set
			{
				if ((this._transaccion_id != value))
				{
					this.Ontransaccion_idChanging(value);
					this.SendPropertyChanging();
					this._transaccion_id = value;
					this.SendPropertyChanged("transaccion_id");
					this.Ontransaccion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura_id", DbType="Int NOT NULL")]
		public int factura_id
		{
			get
			{
				return this._factura_id;
			}
			set
			{
				if ((this._factura_id != value))
				{
					this.Onfactura_idChanging(value);
					this.SendPropertyChanging();
					this._factura_id = value;
					this.SendPropertyChanged("factura_id");
					this.Onfactura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp_comision", DbType="Decimal(8,4) NOT NULL")]
		public decimal mp_comision
		{
			get
			{
				return this._mp_comision;
			}
			set
			{
				if ((this._mp_comision != value))
				{
					this.Onmp_comisionChanging(value);
					this.SendPropertyChanging();
					this._mp_comision = value;
					this.SendPropertyChanged("mp_comision");
					this.Onmp_comisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp_iva", DbType="Decimal(8,4) NOT NULL")]
		public decimal mp_iva
		{
			get
			{
				return this._mp_iva;
			}
			set
			{
				if ((this._mp_iva != value))
				{
					this.Onmp_ivaChanging(value);
					this.SendPropertyChanging();
					this._mp_iva = value;
					this.SendPropertyChanged("mp_iva");
					this.Onmp_ivaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puntos_Ventas")]
	public partial class Puntos_Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _puntoventa_id;
		
		private int _nro_ult_fac_a;
		
		private int _nro_ult_fac_b;
		
		private string _descripcion;
		
		private string _direccion;
		
		private int _cod_postal_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpuntoventa_idChanging(int value);
    partial void Onpuntoventa_idChanged();
    partial void Onnro_ult_fac_aChanging(int value);
    partial void Onnro_ult_fac_aChanged();
    partial void Onnro_ult_fac_bChanging(int value);
    partial void Onnro_ult_fac_bChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Oncod_postal_idChanging(int value);
    partial void Oncod_postal_idChanged();
    #endregion
		
		public Puntos_Ventas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntoventa_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int puntoventa_id
		{
			get
			{
				return this._puntoventa_id;
			}
			set
			{
				if ((this._puntoventa_id != value))
				{
					this.Onpuntoventa_idChanging(value);
					this.SendPropertyChanging();
					this._puntoventa_id = value;
					this.SendPropertyChanged("puntoventa_id");
					this.Onpuntoventa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_ult_fac_a", DbType="Int NOT NULL")]
		public int nro_ult_fac_a
		{
			get
			{
				return this._nro_ult_fac_a;
			}
			set
			{
				if ((this._nro_ult_fac_a != value))
				{
					this.Onnro_ult_fac_aChanging(value);
					this.SendPropertyChanging();
					this._nro_ult_fac_a = value;
					this.SendPropertyChanged("nro_ult_fac_a");
					this.Onnro_ult_fac_aChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_ult_fac_b", DbType="Int NOT NULL")]
		public int nro_ult_fac_b
		{
			get
			{
				return this._nro_ult_fac_b;
			}
			set
			{
				if ((this._nro_ult_fac_b != value))
				{
					this.Onnro_ult_fac_bChanging(value);
					this.SendPropertyChanging();
					this._nro_ult_fac_b = value;
					this.SendPropertyChanged("nro_ult_fac_b");
					this.Onnro_ult_fac_bChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_postal_id", DbType="Int NOT NULL")]
		public int cod_postal_id
		{
			get
			{
				return this._cod_postal_id;
			}
			set
			{
				if ((this._cod_postal_id != value))
				{
					this.Oncod_postal_idChanging(value);
					this.SendPropertyChanging();
					this._cod_postal_id = value;
					this.SendPropertyChanged("cod_postal_id");
					this.Oncod_postal_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Codigos_Iva")]
	public partial class Codigos_Iva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _codigoiva_id;
		
		private string _condicion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigoiva_idChanging(short value);
    partial void Oncodigoiva_idChanged();
    partial void OncondicionChanging(string value);
    partial void OncondicionChanged();
    #endregion
		
		public Codigos_Iva()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoiva_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short codigoiva_id
		{
			get
			{
				return this._codigoiva_id;
			}
			set
			{
				if ((this._codigoiva_id != value))
				{
					this.Oncodigoiva_idChanging(value);
					this.SendPropertyChanging();
					this._codigoiva_id = value;
					this.SendPropertyChanged("codigoiva_id");
					this.Oncodigoiva_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_condicion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string condicion
		{
			get
			{
				return this._condicion;
			}
			set
			{
				if ((this._condicion != value))
				{
					this.OncondicionChanging(value);
					this.SendPropertyChanging();
					this._condicion = value;
					this.SendPropertyChanged("condicion");
					this.OncondicionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contratos")]
	public partial class Contratos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _contrato_id;
		
		private string _denominacion;
		
		private string _direccion;
		
		private int _codpostal_id;
		
		private short _codigoiva_id;
		
		private string _cuit;
		
		private string _telefono;
		
		private string _web;
		
		private string _mail_rendicion_1;
		
		private string _mail_rendicion_2;
		
		private bool _envio_archivo;
		
		private string _mail_ordenpago_1;
		
		private string _mail_ordenpago_2;
		
		private string _mail_confidencial_1;
		
		private string _mail_confidencial_2;
		
		private string _contacto;
		
		private bool _suspendido;
		
		private decimal _porc_administrador;
		
		private string _cbu_1_administrador;
		
		private string _cbu_2_administrador;
		
		private int _concentrador_id;
		
		private int _vendedor_id;
		
		private decimal _porc_descuento;
		
		private string _clave_web;
		
		private string _afip_denominacion;
		
		private string _afip_direccion;
		
		private int _afip_codpostal_id;
		
		private bool _facturar_cons;
		
		private string _usuario_web;
		
		private decimal _ripsa_min;
		
		private decimal _ripsa_porcen;
		
		private decimal _rapipago_min;
		
		private decimal _rapipago_porcen;
		
		private decimal _bapro_min;
		
		private decimal _bapro_porcen;
		
		private decimal _link_min;
		
		private decimal _link_porcen;
		
		private decimal _pagomiscuentas_min;
		
		private decimal _pagomiscuentas_porcen;
		
		private decimal _nacion_min;
		
		private decimal _nacion_porcen;
		
		private decimal _galicia_min;
		
		private decimal _galicia_porcen;
		
		private int _puntoventa_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontrato_idChanging(int value);
    partial void Oncontrato_idChanged();
    partial void OndenominacionChanging(string value);
    partial void OndenominacionChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Oncodpostal_idChanging(int value);
    partial void Oncodpostal_idChanged();
    partial void Oncodigoiva_idChanging(short value);
    partial void Oncodigoiva_idChanged();
    partial void OncuitChanging(string value);
    partial void OncuitChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnwebChanging(string value);
    partial void OnwebChanged();
    partial void Onmail_rendicion_1Changing(string value);
    partial void Onmail_rendicion_1Changed();
    partial void Onmail_rendicion_2Changing(string value);
    partial void Onmail_rendicion_2Changed();
    partial void Onenvio_archivoChanging(bool value);
    partial void Onenvio_archivoChanged();
    partial void Onmail_ordenpago_1Changing(string value);
    partial void Onmail_ordenpago_1Changed();
    partial void Onmail_ordenpago_2Changing(string value);
    partial void Onmail_ordenpago_2Changed();
    partial void Onmail_confidencial_1Changing(string value);
    partial void Onmail_confidencial_1Changed();
    partial void Onmail_confidencial_2Changing(string value);
    partial void Onmail_confidencial_2Changed();
    partial void OncontactoChanging(string value);
    partial void OncontactoChanged();
    partial void OnsuspendidoChanging(bool value);
    partial void OnsuspendidoChanged();
    partial void Onporc_administradorChanging(decimal value);
    partial void Onporc_administradorChanged();
    partial void Oncbu_1_administradorChanging(string value);
    partial void Oncbu_1_administradorChanged();
    partial void Oncbu_2_administradorChanging(string value);
    partial void Oncbu_2_administradorChanged();
    partial void Onconcentrador_idChanging(int value);
    partial void Onconcentrador_idChanged();
    partial void Onvendedor_idChanging(int value);
    partial void Onvendedor_idChanged();
    partial void Onporc_descuentoChanging(decimal value);
    partial void Onporc_descuentoChanged();
    partial void Onclave_webChanging(string value);
    partial void Onclave_webChanged();
    partial void Onafip_denominacionChanging(string value);
    partial void Onafip_denominacionChanged();
    partial void Onafip_direccionChanging(string value);
    partial void Onafip_direccionChanged();
    partial void Onafip_codpostal_idChanging(int value);
    partial void Onafip_codpostal_idChanged();
    partial void Onfacturar_consChanging(bool value);
    partial void Onfacturar_consChanged();
    partial void Onusuario_webChanging(string value);
    partial void Onusuario_webChanged();
    partial void Onripsa_minChanging(decimal value);
    partial void Onripsa_minChanged();
    partial void Onripsa_porcenChanging(decimal value);
    partial void Onripsa_porcenChanged();
    partial void Onrapipago_minChanging(decimal value);
    partial void Onrapipago_minChanged();
    partial void Onrapipago_porcenChanging(decimal value);
    partial void Onrapipago_porcenChanged();
    partial void Onbapro_minChanging(decimal value);
    partial void Onbapro_minChanged();
    partial void Onbapro_porcenChanging(decimal value);
    partial void Onbapro_porcenChanged();
    partial void Onlink_minChanging(decimal value);
    partial void Onlink_minChanged();
    partial void Onlink_porcenChanging(decimal value);
    partial void Onlink_porcenChanged();
    partial void Onpagomiscuentas_minChanging(decimal value);
    partial void Onpagomiscuentas_minChanged();
    partial void Onpagomiscuentas_porcenChanging(decimal value);
    partial void Onpagomiscuentas_porcenChanged();
    partial void Onnacion_minChanging(decimal value);
    partial void Onnacion_minChanged();
    partial void Onnacion_porcenChanging(decimal value);
    partial void Onnacion_porcenChanged();
    partial void Ongalicia_minChanging(decimal value);
    partial void Ongalicia_minChanged();
    partial void Ongalicia_porcenChanging(decimal value);
    partial void Ongalicia_porcenChanged();
    partial void Onpuntoventa_idChanging(int value);
    partial void Onpuntoventa_idChanged();
    #endregion
		
		public Contratos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrato_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int contrato_id
		{
			get
			{
				return this._contrato_id;
			}
			set
			{
				if ((this._contrato_id != value))
				{
					this.Oncontrato_idChanging(value);
					this.SendPropertyChanging();
					this._contrato_id = value;
					this.SendPropertyChanged("contrato_id");
					this.Oncontrato_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denominacion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string denominacion
		{
			get
			{
				return this._denominacion;
			}
			set
			{
				if ((this._denominacion != value))
				{
					this.OndenominacionChanging(value);
					this.SendPropertyChanging();
					this._denominacion = value;
					this.SendPropertyChanged("denominacion");
					this.OndenominacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codpostal_id", DbType="Int NOT NULL")]
		public int codpostal_id
		{
			get
			{
				return this._codpostal_id;
			}
			set
			{
				if ((this._codpostal_id != value))
				{
					this.Oncodpostal_idChanging(value);
					this.SendPropertyChanging();
					this._codpostal_id = value;
					this.SendPropertyChanged("codpostal_id");
					this.Oncodpostal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoiva_id", DbType="SmallInt NOT NULL")]
		public short codigoiva_id
		{
			get
			{
				return this._codigoiva_id;
			}
			set
			{
				if ((this._codigoiva_id != value))
				{
					this.Oncodigoiva_idChanging(value);
					this.SendPropertyChanging();
					this._codigoiva_id = value;
					this.SendPropertyChanged("codigoiva_id");
					this.Oncodigoiva_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuit", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string cuit
		{
			get
			{
				return this._cuit;
			}
			set
			{
				if ((this._cuit != value))
				{
					this.OncuitChanging(value);
					this.SendPropertyChanging();
					this._cuit = value;
					this.SendPropertyChanged("cuit");
					this.OncuitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string web
		{
			get
			{
				return this._web;
			}
			set
			{
				if ((this._web != value))
				{
					this.OnwebChanging(value);
					this.SendPropertyChanging();
					this._web = value;
					this.SendPropertyChanged("web");
					this.OnwebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_rendicion_1", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_rendicion_1
		{
			get
			{
				return this._mail_rendicion_1;
			}
			set
			{
				if ((this._mail_rendicion_1 != value))
				{
					this.Onmail_rendicion_1Changing(value);
					this.SendPropertyChanging();
					this._mail_rendicion_1 = value;
					this.SendPropertyChanged("mail_rendicion_1");
					this.Onmail_rendicion_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_rendicion_2", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_rendicion_2
		{
			get
			{
				return this._mail_rendicion_2;
			}
			set
			{
				if ((this._mail_rendicion_2 != value))
				{
					this.Onmail_rendicion_2Changing(value);
					this.SendPropertyChanging();
					this._mail_rendicion_2 = value;
					this.SendPropertyChanged("mail_rendicion_2");
					this.Onmail_rendicion_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio_archivo", DbType="Bit NOT NULL")]
		public bool envio_archivo
		{
			get
			{
				return this._envio_archivo;
			}
			set
			{
				if ((this._envio_archivo != value))
				{
					this.Onenvio_archivoChanging(value);
					this.SendPropertyChanging();
					this._envio_archivo = value;
					this.SendPropertyChanged("envio_archivo");
					this.Onenvio_archivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_ordenpago_1", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_ordenpago_1
		{
			get
			{
				return this._mail_ordenpago_1;
			}
			set
			{
				if ((this._mail_ordenpago_1 != value))
				{
					this.Onmail_ordenpago_1Changing(value);
					this.SendPropertyChanging();
					this._mail_ordenpago_1 = value;
					this.SendPropertyChanged("mail_ordenpago_1");
					this.Onmail_ordenpago_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_ordenpago_2", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_ordenpago_2
		{
			get
			{
				return this._mail_ordenpago_2;
			}
			set
			{
				if ((this._mail_ordenpago_2 != value))
				{
					this.Onmail_ordenpago_2Changing(value);
					this.SendPropertyChanging();
					this._mail_ordenpago_2 = value;
					this.SendPropertyChanged("mail_ordenpago_2");
					this.Onmail_ordenpago_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_confidencial_1", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_confidencial_1
		{
			get
			{
				return this._mail_confidencial_1;
			}
			set
			{
				if ((this._mail_confidencial_1 != value))
				{
					this.Onmail_confidencial_1Changing(value);
					this.SendPropertyChanging();
					this._mail_confidencial_1 = value;
					this.SendPropertyChanged("mail_confidencial_1");
					this.Onmail_confidencial_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_confidencial_2", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mail_confidencial_2
		{
			get
			{
				return this._mail_confidencial_2;
			}
			set
			{
				if ((this._mail_confidencial_2 != value))
				{
					this.Onmail_confidencial_2Changing(value);
					this.SendPropertyChanging();
					this._mail_confidencial_2 = value;
					this.SendPropertyChanged("mail_confidencial_2");
					this.Onmail_confidencial_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacto", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string contacto
		{
			get
			{
				return this._contacto;
			}
			set
			{
				if ((this._contacto != value))
				{
					this.OncontactoChanging(value);
					this.SendPropertyChanging();
					this._contacto = value;
					this.SendPropertyChanged("contacto");
					this.OncontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspendido", DbType="Bit NOT NULL")]
		public bool suspendido
		{
			get
			{
				return this._suspendido;
			}
			set
			{
				if ((this._suspendido != value))
				{
					this.OnsuspendidoChanging(value);
					this.SendPropertyChanging();
					this._suspendido = value;
					this.SendPropertyChanged("suspendido");
					this.OnsuspendidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porc_administrador", DbType="Decimal(5,2) NOT NULL")]
		public decimal porc_administrador
		{
			get
			{
				return this._porc_administrador;
			}
			set
			{
				if ((this._porc_administrador != value))
				{
					this.Onporc_administradorChanging(value);
					this.SendPropertyChanging();
					this._porc_administrador = value;
					this.SendPropertyChanged("porc_administrador");
					this.Onporc_administradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbu_1_administrador", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string cbu_1_administrador
		{
			get
			{
				return this._cbu_1_administrador;
			}
			set
			{
				if ((this._cbu_1_administrador != value))
				{
					this.Oncbu_1_administradorChanging(value);
					this.SendPropertyChanging();
					this._cbu_1_administrador = value;
					this.SendPropertyChanged("cbu_1_administrador");
					this.Oncbu_1_administradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbu_2_administrador", DbType="Char(14) NOT NULL", CanBeNull=false)]
		public string cbu_2_administrador
		{
			get
			{
				return this._cbu_2_administrador;
			}
			set
			{
				if ((this._cbu_2_administrador != value))
				{
					this.Oncbu_2_administradorChanging(value);
					this.SendPropertyChanging();
					this._cbu_2_administrador = value;
					this.SendPropertyChanged("cbu_2_administrador");
					this.Oncbu_2_administradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concentrador_id", DbType="Int NOT NULL")]
		public int concentrador_id
		{
			get
			{
				return this._concentrador_id;
			}
			set
			{
				if ((this._concentrador_id != value))
				{
					this.Onconcentrador_idChanging(value);
					this.SendPropertyChanging();
					this._concentrador_id = value;
					this.SendPropertyChanged("concentrador_id");
					this.Onconcentrador_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor_id", DbType="Int NOT NULL")]
		public int vendedor_id
		{
			get
			{
				return this._vendedor_id;
			}
			set
			{
				if ((this._vendedor_id != value))
				{
					this.Onvendedor_idChanging(value);
					this.SendPropertyChanging();
					this._vendedor_id = value;
					this.SendPropertyChanged("vendedor_id");
					this.Onvendedor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porc_descuento", DbType="Decimal(5,2) NOT NULL")]
		public decimal porc_descuento
		{
			get
			{
				return this._porc_descuento;
			}
			set
			{
				if ((this._porc_descuento != value))
				{
					this.Onporc_descuentoChanging(value);
					this.SendPropertyChanging();
					this._porc_descuento = value;
					this.SendPropertyChanged("porc_descuento");
					this.Onporc_descuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave_web", DbType="VarChar(50)")]
		public string clave_web
		{
			get
			{
				return this._clave_web;
			}
			set
			{
				if ((this._clave_web != value))
				{
					this.Onclave_webChanging(value);
					this.SendPropertyChanging();
					this._clave_web = value;
					this.SendPropertyChanged("clave_web");
					this.Onclave_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_afip_denominacion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string afip_denominacion
		{
			get
			{
				return this._afip_denominacion;
			}
			set
			{
				if ((this._afip_denominacion != value))
				{
					this.Onafip_denominacionChanging(value);
					this.SendPropertyChanging();
					this._afip_denominacion = value;
					this.SendPropertyChanged("afip_denominacion");
					this.Onafip_denominacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_afip_direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string afip_direccion
		{
			get
			{
				return this._afip_direccion;
			}
			set
			{
				if ((this._afip_direccion != value))
				{
					this.Onafip_direccionChanging(value);
					this.SendPropertyChanging();
					this._afip_direccion = value;
					this.SendPropertyChanged("afip_direccion");
					this.Onafip_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_afip_codpostal_id", DbType="Int NOT NULL")]
		public int afip_codpostal_id
		{
			get
			{
				return this._afip_codpostal_id;
			}
			set
			{
				if ((this._afip_codpostal_id != value))
				{
					this.Onafip_codpostal_idChanging(value);
					this.SendPropertyChanging();
					this._afip_codpostal_id = value;
					this.SendPropertyChanged("afip_codpostal_id");
					this.Onafip_codpostal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facturar_cons", DbType="Bit NOT NULL")]
		public bool facturar_cons
		{
			get
			{
				return this._facturar_cons;
			}
			set
			{
				if ((this._facturar_cons != value))
				{
					this.Onfacturar_consChanging(value);
					this.SendPropertyChanging();
					this._facturar_cons = value;
					this.SendPropertyChanged("facturar_cons");
					this.Onfacturar_consChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_web", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario_web
		{
			get
			{
				return this._usuario_web;
			}
			set
			{
				if ((this._usuario_web != value))
				{
					this.Onusuario_webChanging(value);
					this.SendPropertyChanging();
					this._usuario_web = value;
					this.SendPropertyChanged("usuario_web");
					this.Onusuario_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ripsa_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal ripsa_min
		{
			get
			{
				return this._ripsa_min;
			}
			set
			{
				if ((this._ripsa_min != value))
				{
					this.Onripsa_minChanging(value);
					this.SendPropertyChanging();
					this._ripsa_min = value;
					this.SendPropertyChanged("ripsa_min");
					this.Onripsa_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ripsa_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal ripsa_porcen
		{
			get
			{
				return this._ripsa_porcen;
			}
			set
			{
				if ((this._ripsa_porcen != value))
				{
					this.Onripsa_porcenChanging(value);
					this.SendPropertyChanging();
					this._ripsa_porcen = value;
					this.SendPropertyChanged("ripsa_porcen");
					this.Onripsa_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapipago_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal rapipago_min
		{
			get
			{
				return this._rapipago_min;
			}
			set
			{
				if ((this._rapipago_min != value))
				{
					this.Onrapipago_minChanging(value);
					this.SendPropertyChanging();
					this._rapipago_min = value;
					this.SendPropertyChanged("rapipago_min");
					this.Onrapipago_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapipago_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal rapipago_porcen
		{
			get
			{
				return this._rapipago_porcen;
			}
			set
			{
				if ((this._rapipago_porcen != value))
				{
					this.Onrapipago_porcenChanging(value);
					this.SendPropertyChanging();
					this._rapipago_porcen = value;
					this.SendPropertyChanged("rapipago_porcen");
					this.Onrapipago_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bapro_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal bapro_min
		{
			get
			{
				return this._bapro_min;
			}
			set
			{
				if ((this._bapro_min != value))
				{
					this.Onbapro_minChanging(value);
					this.SendPropertyChanging();
					this._bapro_min = value;
					this.SendPropertyChanged("bapro_min");
					this.Onbapro_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bapro_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal bapro_porcen
		{
			get
			{
				return this._bapro_porcen;
			}
			set
			{
				if ((this._bapro_porcen != value))
				{
					this.Onbapro_porcenChanging(value);
					this.SendPropertyChanging();
					this._bapro_porcen = value;
					this.SendPropertyChanged("bapro_porcen");
					this.Onbapro_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal link_min
		{
			get
			{
				return this._link_min;
			}
			set
			{
				if ((this._link_min != value))
				{
					this.Onlink_minChanging(value);
					this.SendPropertyChanging();
					this._link_min = value;
					this.SendPropertyChanged("link_min");
					this.Onlink_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal link_porcen
		{
			get
			{
				return this._link_porcen;
			}
			set
			{
				if ((this._link_porcen != value))
				{
					this.Onlink_porcenChanging(value);
					this.SendPropertyChanging();
					this._link_porcen = value;
					this.SendPropertyChanged("link_porcen");
					this.Onlink_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagomiscuentas_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal pagomiscuentas_min
		{
			get
			{
				return this._pagomiscuentas_min;
			}
			set
			{
				if ((this._pagomiscuentas_min != value))
				{
					this.Onpagomiscuentas_minChanging(value);
					this.SendPropertyChanging();
					this._pagomiscuentas_min = value;
					this.SendPropertyChanged("pagomiscuentas_min");
					this.Onpagomiscuentas_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagomiscuentas_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal pagomiscuentas_porcen
		{
			get
			{
				return this._pagomiscuentas_porcen;
			}
			set
			{
				if ((this._pagomiscuentas_porcen != value))
				{
					this.Onpagomiscuentas_porcenChanging(value);
					this.SendPropertyChanging();
					this._pagomiscuentas_porcen = value;
					this.SendPropertyChanged("pagomiscuentas_porcen");
					this.Onpagomiscuentas_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacion_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal nacion_min
		{
			get
			{
				return this._nacion_min;
			}
			set
			{
				if ((this._nacion_min != value))
				{
					this.Onnacion_minChanging(value);
					this.SendPropertyChanging();
					this._nacion_min = value;
					this.SendPropertyChanged("nacion_min");
					this.Onnacion_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacion_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal nacion_porcen
		{
			get
			{
				return this._nacion_porcen;
			}
			set
			{
				if ((this._nacion_porcen != value))
				{
					this.Onnacion_porcenChanging(value);
					this.SendPropertyChanging();
					this._nacion_porcen = value;
					this.SendPropertyChanged("nacion_porcen");
					this.Onnacion_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galicia_min", DbType="Decimal(4,2) NOT NULL")]
		public decimal galicia_min
		{
			get
			{
				return this._galicia_min;
			}
			set
			{
				if ((this._galicia_min != value))
				{
					this.Ongalicia_minChanging(value);
					this.SendPropertyChanging();
					this._galicia_min = value;
					this.SendPropertyChanged("galicia_min");
					this.Ongalicia_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galicia_porcen", DbType="Decimal(6,4) NOT NULL")]
		public decimal galicia_porcen
		{
			get
			{
				return this._galicia_porcen;
			}
			set
			{
				if ((this._galicia_porcen != value))
				{
					this.Ongalicia_porcenChanging(value);
					this.SendPropertyChanging();
					this._galicia_porcen = value;
					this.SendPropertyChanged("galicia_porcen");
					this.Ongalicia_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntoventa_id", DbType="Int NOT NULL")]
		public int puntoventa_id
		{
			get
			{
				return this._puntoventa_id;
			}
			set
			{
				if ((this._puntoventa_id != value))
				{
					this.Onpuntoventa_idChanging(value);
					this.SendPropertyChanging();
					this._puntoventa_id = value;
					this.SendPropertyChanged("puntoventa_id");
					this.Onpuntoventa_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Facturas")]
	public partial class Facturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _factura_id;
		
		private int _puntoventa_id;
		
		private int _nro_factura;
		
		private char _tipo_factura;
		
		private System.DateTime _fecha;
		
		private int _contrato_id;
		
		private string _concepto;
		
		private decimal _importe;
		
		private decimal _iva;
		
		private decimal _neto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfactura_idChanging(int value);
    partial void Onfactura_idChanged();
    partial void Onpuntoventa_idChanging(int value);
    partial void Onpuntoventa_idChanged();
    partial void Onnro_facturaChanging(int value);
    partial void Onnro_facturaChanged();
    partial void Ontipo_facturaChanging(char value);
    partial void Ontipo_facturaChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Oncontrato_idChanging(int value);
    partial void Oncontrato_idChanged();
    partial void OnconceptoChanging(string value);
    partial void OnconceptoChanged();
    partial void OnimporteChanging(decimal value);
    partial void OnimporteChanged();
    partial void OnivaChanging(decimal value);
    partial void OnivaChanged();
    partial void OnnetoChanging(decimal value);
    partial void OnnetoChanged();
    #endregion
		
		public Facturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int factura_id
		{
			get
			{
				return this._factura_id;
			}
			set
			{
				if ((this._factura_id != value))
				{
					this.Onfactura_idChanging(value);
					this.SendPropertyChanging();
					this._factura_id = value;
					this.SendPropertyChanged("factura_id");
					this.Onfactura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntoventa_id", DbType="Int NOT NULL")]
		public int puntoventa_id
		{
			get
			{
				return this._puntoventa_id;
			}
			set
			{
				if ((this._puntoventa_id != value))
				{
					this.Onpuntoventa_idChanging(value);
					this.SendPropertyChanging();
					this._puntoventa_id = value;
					this.SendPropertyChanged("puntoventa_id");
					this.Onpuntoventa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_factura", DbType="Int NOT NULL")]
		public int nro_factura
		{
			get
			{
				return this._nro_factura;
			}
			set
			{
				if ((this._nro_factura != value))
				{
					this.Onnro_facturaChanging(value);
					this.SendPropertyChanging();
					this._nro_factura = value;
					this.SendPropertyChanged("nro_factura");
					this.Onnro_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_factura", DbType="Char(1) NOT NULL")]
		public char tipo_factura
		{
			get
			{
				return this._tipo_factura;
			}
			set
			{
				if ((this._tipo_factura != value))
				{
					this.Ontipo_facturaChanging(value);
					this.SendPropertyChanging();
					this._tipo_factura = value;
					this.SendPropertyChanged("tipo_factura");
					this.Ontipo_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrato_id", DbType="Int NOT NULL")]
		public int contrato_id
		{
			get
			{
				return this._contrato_id;
			}
			set
			{
				if ((this._contrato_id != value))
				{
					this.Oncontrato_idChanging(value);
					this.SendPropertyChanging();
					this._contrato_id = value;
					this.SendPropertyChanged("contrato_id");
					this.Oncontrato_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concepto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				if ((this._concepto != value))
				{
					this.OnconceptoChanging(value);
					this.SendPropertyChanging();
					this._concepto = value;
					this.SendPropertyChanged("concepto");
					this.OnconceptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_importe", DbType="Decimal(8,2) NOT NULL")]
		public decimal importe
		{
			get
			{
				return this._importe;
			}
			set
			{
				if ((this._importe != value))
				{
					this.OnimporteChanging(value);
					this.SendPropertyChanging();
					this._importe = value;
					this.SendPropertyChanged("importe");
					this.OnimporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iva", DbType="Decimal(8,2) NOT NULL")]
		public decimal iva
		{
			get
			{
				return this._iva;
			}
			set
			{
				if ((this._iva != value))
				{
					this.OnivaChanging(value);
					this.SendPropertyChanging();
					this._iva = value;
					this.SendPropertyChanged("iva");
					this.OnivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neto", DbType="Decimal(8,2) NOT NULL")]
		public decimal neto
		{
			get
			{
				return this._neto;
			}
			set
			{
				if ((this._neto != value))
				{
					this.OnnetoChanging(value);
					this.SendPropertyChanging();
					this._neto = value;
					this.SendPropertyChanged("neto");
					this.OnnetoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
